### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by testuser12345gfd** [RewardedIvan/3DPS#1]
**Describe the bug**

**To Reproduce**
1. build and start server
2. try to upload level
3. error

**Expected behavior**
no errors and level gets uploaded

**Server (please complete the following information):**
 - OS: ubuntu 16.04

**Additional context**
2022/08/23 23:32:53 http: panic serving 192.168.1.1:57393: runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
net/http.(*conn).serve.func1()
        /snap/go/9952/src/net/http/server.go:1825 +0xbf
panic({0x7b7120, 0xc42fa0})
        /snap/go/9952/src/runtime/panic.go:844 +0x258
main.EDB({0x8049f0, 0x20}, 0x7fa778?, {0xc0001a0000, 0x4be})
        /3dps/3dps.go:45 +0x162
main.postLevel({0x8848d0, 0xc0001822a0}, 0xc0000feb00)
        /3dps/3dps.go:114 +0x20c
net/http.HandlerFunc.ServeHTTP(0x72?, {0x8848d0?, 0xc0001822a0?}, 0xc000078260?)
        /snap/go/9952/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x8848d0, 0xc0001822a0}, 0xc0000feb00)
        /snap/go/9952/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x883c40?}, {0x8848d0, 0xc0001822a0}, 0xc0000feb00)
        /snap/go/9952/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00007c1e0, {0x884a98, 0xc000094f90})
        /snap/go/9952/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /snap/go/9952/src/net/http/server.go:3071 +0x4db

**Comment by testuser12345gfd** [comment]
fixed i was stupid

**Comment by RewardedIvan** [comment]
~Sorry to hear, but I am quite inactive at times, this is still an issue, since the server is really unstable right now. As the recent levels don't work yet.~ Please upgrade Ubuntu
